name: "Run tests"

on:
  push:
    branches: [ cookiecutter ]
  pull_request:
    branches: [ cookiecutter ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Sort imports with isort
      run: |
        pip install isort
        isort .
